version: '3.8'

services:
  landing_app:
    build:
      context: .
      dockerfile: .deploy/Dockerfile
    container_name: landing_app
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
    volumes:
      - .:/var/www/html
      - landing-public:/var/www/html/public   # ✅ Volumen externo aislado
    ports:
      - "${APP_EXTERNAL_PORT}:${APP_PORT}"
    depends_on:
      - landing_db
      - landing_redis
    networks:
      - proxy_net

  landing_db:
    image: mysql:8.0
    container_name: landing_db
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - landing_db_data:/var/lib/mysql
    networks:
      - proxy_net

  landing_redis:
    image: redis:7-alpine
    container_name: landing_redis
    ports:
      - "6387:6379"
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true

volumes:
  landing_db_data:
  landing-public:
    external: true
    name: landing-public
